
server:
  port: 7071

message: Development mode is on

spring:
  application:
    name: Abstract-Auditable-Entity(Development)

  datasource:
    url: jdbc:mysql://localhost:3306/database_dev
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true



#
#server.port=7071
#
#spring.application.name=Abstract-Auditable-Entity(Development)
#
#spring.datasource.url = jdbc:mysql://localhost:3306/database_dev
#spring.datasource.username = root
#spring.datasource.password = root
#
### Hibernate Properties
## The SQL dialect makes Hibernate generate better SQL for the chosen database
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
#
## Hibernate ddl auto (create, create-drop, validate, update)
#spring.jpa.hibernate.ddl-auto = update
#spring.jpa.show-sql=true